title: "Video-Electroencephalogram (VEEG)"
requested_by: "Dr. Danilo Fonseca Maia"
sample_date: "2023-10-20"
results:
- metric: "Base Activity"
  material: "N/A"
  result: "Normal"
  result_unit: "N/A"
  reference_range_min: "N/A"
  reference_range_max: "N/A"
  result_status: "Normal"
  observations: "Normal base activity observed during wakefulness, drowsiness, and sleep."
- metric: "Epileptiform Abnormalities"
  material: "N/A"
  result: "Absent"
  result_unit: "N/A"
  reference_range_min: "N/A"
  reference_range_max: "N/A"
  result_status: "Normal"
  observations: "No epileptiform abnormalities observed."
- metric: "Electrographic Seizures"
  material: "N/A"
  result: "Absent"
  result_unit: "N/A"
  reference_range_min: "N/A"
  reference_range_max: "N/A"
  result_status: "Normal"
  observations: "No electrographic seizures recorded."
- metric: "Photostimulation Response"
  material: "N/A"
  result: "No abnormal responses"
  result_unit: "N/A"
  reference_range_min: "N/A"
  reference_range_max: "N/A"
  result_status: "Normal"
  observations: "No abnormal responses elicited by photostimulation."