title: "Microbial Organic Acids Test"
requested_by: "Unknown"
sample_date: "Unknown"
results:
- metric: "3-Oxoglutaric"
  material: "urine"
  result: "10"
  result_unit: "N/A"
  reference_range_min: "N/A"
  reference_range_max: "N/A"
  result_status: "High"
  observations: "Proliferation indication"
- metric: "Furan-2,5-dicarboxylic"
  material: "urine"
  result: "N/A"
  result_unit: "N/A"
  reference_range_min: "N/A"
  reference_range_max: "N/A"
  result_status: "N/A"
  observations: "N/A"
- metric: "Arabinose"
  material: "urine"
  result: "High"
  result_unit: "N/A"
  reference_range_min: "N/A"
  reference_range_max: "N/A"
  result_status: "High"
  observations: "N/A"
- metric: "Hippuric"
  material: "urine"
  result: "<a"
  result_unit: "N/A"
  reference_range_min: "N/A"
  reference_range_max: "N/A"
  result_status: "Low"
  observations: "N/A"
- metric: "DHPPA"
  material: "urine"
  result: "<0"
  result_unit: "N/A"
  reference_range_min: "N/A"
  reference_range_max: "N/A"
  result_status: "Low"
  observations: "N/A"