title: "Genetic Sequencing Analysis"
requested_by: "Tony Callleri França"
sample_date: "2024-01-23"
results:
- metric: "GALT Variant"
  material: "DNA"
  result: "NM_000155:c.C404T (p.S135L)"
  result_unit: "N/A"
  reference_range_min: "N/A"
  reference_range_max: "N/A"
  result_status: "Pathogenic"
  observations: "Associated with Galactosemia – AR (OMIM: 230400)"
- metric: "MED13 Variant"
  material: "DNA"
  result: "NM_005121:c.A866T (p.D289V)"
  result_unit: "N/A"
  reference_range_min: "N/A"
  reference_range_max: "N/A"
  result_status: "Uncertain Significance"
  observations: "Associated with Intellectual Development Disorder – AD (OMIM: 618009)"
- metric: "ASS1 Variant"
  material: "DNA"
  result: "NM_054012:c.G299A (p.R100H)"
  result_unit: "N/A"
  reference_range_min: "N/A"
  reference_range_max: "N/A"
  result_status: "Uncertain Significance"
  observations: "Associated with Citrulinemia - AR (OMIM: 215700)"
- metric: "TAT Variant"
  material: "DNA"
  result: "NM_000353:c.G998A (p.R333H)"
  result_unit: "N/A"
  reference_range_min: "N/A"
  reference_range_max: "N/A"
  result_status: "Uncertain Significance"
  observations: "Associated with Tyrosinemia, type II – AR (OMIM: 276600)"
- metric: "FHL1 Variant"
  material: "DNA"
  result: "NM_001159699:c.A665G (p.Q222R)"
  result_unit: "N/A"
  reference_range_min: "N/A"
  reference_range_max: "N/A"
  result_status: "Uncertain Significance"
  observations: "Associated with Emery-Dreifuss Muscular Dystrophy, type 6 – LXR"
- metric: "DLGAP1 Variant"
  material: "DNA"
  result: "NM_001242761:c.A850G (p.T284A)"
  result_unit: "N/A"
  reference_range_min: "N/A"
  reference_range_max: "N/A"
  result_status: "Uncertain Significance"
  observations: "Associated with Autism Spectrum Disorder (Score 2)"