title: "Video-EEG 12 Hours"
requested_by: "Unknown"
sample_date: "2023-10-21"
results:
- metric: "Fp1-F3"
  material: "N/A"
  result: "Multiple time markers recorded"
  result_unit: "µV"
  reference_range_min: "Unknown"
  reference_range_max: "Unknown"
  result_status: "Indeterminate"
  observations: "N/A"
- metric: "F3-C3"
  material: "N/A"
  result: "Multiple time markers recorded"
  result_unit: "µV"
  reference_range_min: "Unknown"
  reference_range_max: "Unknown"
  result_status: "Indeterminate"
  observations: "N/A"
- metric: "C3-P3"
  material: "N/A"
  result: "Multiple time markers recorded"
  result_unit: "µV"
  reference_range_min: "Unknown"
  reference_range_max: "Unknown"
  result_status: "Indeterminate"
  observations: "N/A"
- metric: "P3-O1"
  material: "N/A"
  result: "Multiple time markers recorded"
  result_unit: "µV"
  reference_range_min: "Unknown"
  reference_range_max: "Unknown"
  result_status: "Indeterminate"
  observations: "N/A"
- metric: "Fp1-F7"
  material: "N/A"
  result: "Multiple time markers recorded"
  result_unit: "µV"
  reference_range_min: "Unknown"
  reference_range_max: "Unknown"
  result_status: "Indeterminate"
  observations: "N/A"
observations: "This video-EEG report includes multiple EEG phases recorded for a patient named ISAAC LOBATO FRANCA, aged 4 years. Specific metrics are related to electrode placement and recording periods."